svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/BUILD_20041002/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/BUILD_20041005/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/INIT_BUILD/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/Initial/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_BUILD_20040416/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_BUILD_20040607/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_OTLK_REL_20040803_VER1_2/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_OTLK_REL_20041111_VER1_3_3/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_OTLK_REL_20041207_VER1_3_7/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_PPC_BUILD_20041021_1_6/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_PPC_REL_20040806_VER1_5/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_PPC_REL_20041111_VER1_6_3/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SC_PPC_REL_20041207_VER1_6_3/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SP_SC_ACI_2_5_20040309/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SP_SC_API_2_3_20031118/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/SP_SC_API_2_5_20040129/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/bbplugin_import/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/bbplugin_3_0_6a/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_0_1b4/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_0_2b1/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_1_0/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_1_1/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_1_2/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_1_5/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_20021231/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_20030110/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_20030124/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_20030131/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_2_0/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_12/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_15/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_16/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_3/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_3_b/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_3_b2/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_4/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_4_b2/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_5/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_6/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_7/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_0_9/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/culhwch_4_1_0/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/first-release/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/first_release/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/first_version/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/fmail-import/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/forge_20030731/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/ftypes/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/import/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/initial/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/initial-revision/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/initial_version/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/jmc_barcelona_5/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlook_pre_char/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_20/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_21/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_22/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_24/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_25/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_26/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_27/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_28/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_29/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_30/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_31/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_32/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/outlookclient_2_0_33/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/sc_demo_build_20041015/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/syncevolution-0-4/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/syncevolution-0-4-pre2/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/syncevolution-0-5/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/t_checkpoint_1/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/t_checkpoint_2/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/t_mergedfrom_659/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/wm_before_all_mods/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/wm_before_new_startsync/
svn del -m "Unused tag removed" https://core.forge.funambol.org/svn/core/top-level/tags/wm_newconfig_base/
