svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.1.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.10.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.10.2.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.10.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.10.4.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.11.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.11.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.15.2.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.16.2.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.18.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.2.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.2.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.3.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.3.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.34.2.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.4.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.4.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.4.4.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.5.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.6.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.6.2.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.7.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.8.2.1.2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.8.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/unlabeled-1.9.4/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/INIT/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/Sync4j-ext/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/Sync4j_2_0/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/admin_1_0_6/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/b_char/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/b_demo302/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/b_leak/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/b_memtest_ex/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/b_newconfig/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/b_wmplugin_pre_alpha1/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/blackberryclient_branch_1_1_10/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/dist_4_0_5/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/e_6_0_1_newUI/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/e_6_0_8_UIfixes/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/experimental/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/foundation-1_1_1/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/foundation_1_2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/foundation_1_3/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/funambol_initial/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/initial_release/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/syncserver401_scts/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/syncserver_403b2/
svn del -m "Unused branch removed" https://core.forge.funambol.org/svn/core/top-level/branches/syncserver_4_0_5/

