svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_1_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_1_2_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_20040707/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin_20040806_v105/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/admin-20040705/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/apinative_1_1_10/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/apinative_1_1_11/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/apinative_1_1_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_10/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_1_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_2_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/blackberryclient_1_2_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/buid_20020408/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20020323/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20020408/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20020706/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20020809/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20021007/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20021031/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20021102/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20021218/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030222/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030502/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030528/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030604/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030605/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030617/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030703/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030710/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030721/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030731/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20030804/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20031013/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20031030/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20031102/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20031209/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20031212/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040107/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040113/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040126/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040216/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040227/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040305/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040309/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040318/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040415/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040423/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040514/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040520/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040528/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_200407013/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040705/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040707/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040713/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_20040728/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040130/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040209/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040325/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040415/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040630/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040708/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_0_20040727/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_20040806/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_20041025/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_20041028/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_20041029/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_4_20041102/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_5_20041111/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_6_20041112/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_6_20041122/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/build_scapinative_1_1_7_20041123/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dbconnector_1_0_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030502/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030604/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030605/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030617/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030710/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030731/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20030804/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20031013/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20031030/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20031209/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040107/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040113/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040216/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040227/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040309/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040318/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040415/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040423/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040514/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040520/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040528/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040612/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_200407013/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040705/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040707/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040713/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_20040728/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_0_6_20041202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_0_6_20041213/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_0_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_0_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_0_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_4_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_scapinative_1_0_20040130/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dist_scapinative_1_0_20040209/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20030502/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20030605/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20030617/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20030731/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20030809/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20031030/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20031209/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040107/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040113/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040216/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040227/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040309/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040415/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040423/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040514/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_200407013/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040705/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040707/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040713/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_20040728/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_0_6_20041202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_0_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_0_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_0_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_2_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/docs_4_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummy_1_1_20041107/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummy_1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummy_1_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummy_1_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummy_1_2_20041107/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummy_1_2_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_2_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/dummyconnector_1_3_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/emailgateway_1_0_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/emailgateway_1_0_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/emailgateway_1_0_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/emailgateway_1_0_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/emailgateway_1_0_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/emailgateway_1_0_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_2_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_2_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/exchangeconnector_1_3_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ext_1_0_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ext_1_0_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ext_1_0_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ext_20040705/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ext_20040707/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/fondation_20050509/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/fondation_sp_20050511/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation-1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation-1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation-1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_1_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_1_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_1_5_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_1_5_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_1_6_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_1_7_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_sp_20050512/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/foundation_sp_20050513/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_10/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_11/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_12/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_13/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_14/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_15/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_16/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_0_17/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/ipodclient_1_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2meapi_2_7_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2meapi_2_7_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2seapi_2_8_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2seapi_2_8_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2seapi_2_8_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2seapi_2_8_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2seapi_2_8_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/j2seapi_2_8_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_10/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_11/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_12/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_0_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/javaguiclient_1_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/mods_20030731/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/modules_20040705/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_1_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pimweb_1_2_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_10/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/pocketpcclient_1_7_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverdm_1_4_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverdm_1_4_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverdm_1_4_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverdm_1_4_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverdm_1_4_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverdm_1_4_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_2_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_2_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_2_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_5_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_5_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_5_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_5_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_5_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/serverds_4_5_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2me_2_5_20040409/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2me_2_5_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2me_2_6_20040805/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2me_2_7_20041008/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_5_20040409/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_5_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_6_20040805/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_7_20041010/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_7_20041105/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_7_20041106/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_7_20041107/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_7_20041108/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api-j2se_2_7_20041110/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-api_2_5_2004_04_09/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-cle_1_0_20040413/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-cle_1_0_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-cle_1_1_20040805/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-conduit_1_3_20040413/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-conduit_1_4_20040805/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client-demo_1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-client_1_3_20040414/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-bb_1_0_20041108/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-bb_1_0_20041111/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-cle_1_1_20041104/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-cle_1_2_20041104/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041016/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041017/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041018/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041020/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041029/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041102/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041103/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041104/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041108/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j-syncclient-demo_1_0_20041111/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j21ga/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j22b1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j22b2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j22b3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j22b4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j22b5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23a1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23a1_20050610/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23a2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23b1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23b2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23b3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23b4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4j23ga/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/sync4jadmin_1_1_1_20041202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncadmin-1_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncadmin_1_1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncadmin_1_1_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-api-native_118/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-api-native_118_20050202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-api-native_119/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-outlook_138/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-outlook_138_20050202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-outlook_140/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-outlook_143/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-ppc_164/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-ppc_164_20050202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-ppc_165/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclient-pim-ppc_166/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapij2se_2_7_1_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapij2se_2_7_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapij2se_2_7_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapij2se_2_8_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapinative_117/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapinative_118/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2me_2_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2me_2_7_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2me_2_7_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2me_2_7_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2me_2_7_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2me_2_7_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientapj2se_2_7_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientcle_1_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientcle_1_2_1_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientcle_1_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientcle_1_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientcle_1_2_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimblackberry_1_0_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimblackberry_1_0_1_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimblackberry_1_0_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimblackberry_1_1_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimblackberry_1_1_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimblackberry_1_1_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimdemo_1_0_1_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimdemo_1_0_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimdemo_1_0_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncclientpimdemo_1_0_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_0_20040303/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_0_20040607/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_1_20040805/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_2_1_20041201/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_2_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_2_20041105/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_2_3/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncconnectorexchange_1_2_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncserver401_scts_final/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncserver_4_0_6_20041202/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncserver_4_0_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncserver_4_0_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/syncserver_4_0_9/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_0/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_2/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_4/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_5/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_6/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_7/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/test_2_3_8/ https://core.forge.funambol.org/svn/core/sync4j/tags/.
svn mv -m "Sync4j tags moved to the new root" https://core.forge.funambol.org/svn/core/top-level/tags/wm_1_12_0_1/ https://core.forge.funambol.org/svn/core/sync4j/tags/.

